-- Auto-generated by build_aw_textbook_reference.py
-- Maps Step 1 semantic Div classes to Word custom styles for Pandoc DOCX output.
local style_for_class = {
  ["learn-process"] = "Learn Process",
  ["learn-language"] = "Learn Language",
  ["learn-principle"] = "Learn Principle",
  ["learn-transfer"] = "Learn Transfer",
  ["learn-teaching"] = "Learn Teaching",
  ["learn-note"] = "Learn Note",
  ["guidance-step"] = "Guidance Step",
  ["reference-support"] = "Reference Support",
  ["rubric-assessment"] = "Rubric Assessment",
  ["course-meta"] = "Course Meta",
  ["activity-input"] = "Activity Input",
  ["activity-analysis"] = "Activity Analysis",
  ["activity-language-control"] = "Activity Language Control",
  ["activity-rewrite"] = "Activity Rewrite",
  ["activity-edit"] = "Activity Edit",
  ["activity-draft"] = "Activity Draft",
  ["model"] = "Model",
  ["model-bad"] = "Model Bad",
  ["model-good"] = "Model Good",
  ["worked-example"] = "Worked Example",
  ["example"] = "Example",
  ["placeholder"] = "Placeholder",
  ["self-study"] = "Self Study",
  ["annotation"] = "Annotation",
}

-- The book source uses standalone --- as combined-draft separators.
-- They must not become Word page breaks or visible horizontal rules.
function HorizontalRule(el)
  return {}
end

-- Avoid Pandoc's direct bold/italic output overriding the lighter Word style system.
function Strong(el)
  return el
end

function Emph(el)
  return el
end

local function preserve_div_line_breaks(el)
  return pandoc.walk_block(el, {
    SoftBreak = function(_)
      return pandoc.LineBreak()
    end
  })
end

function Div(el)
  for _, class in ipairs(el.classes) do
    local style = style_for_class[class]
    if style then
      el.attributes['custom-style'] = style
      return preserve_div_line_breaks(el)
    end
  end
  return el
end
