"""
Claude edit
Simple CLI wrapper that calls `pandoc` to convert Markdown to DOCX using a `reference.docx`.
- Requires `pandoc` installed and on PATH.
- Produces a `.docx` with an autogenerated TOC when `--toc` is set.

Usage example:
python scripts/cli.py --input "chapter1.md" --output "Book.docx" --reference reference.docx --toc
"""
from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Iterable, List


def check_pandoc() -> None:
    if shutil.which('pandoc') is None:
        print('Error: pandoc binary not found on PATH. Install from https://pandoc.org/installing.html')
        sys.exit(2)


def build_pandoc_cmd(
    input_path: Path,
    output_path: Path,
    reference: Path,
    toc: bool,
    toc_depth: int,
) -> List[str]:
    # Disable YAML metadata blocks so in-document `---` separators are not parsed as YAML.
    # This avoids errors like `Unknown alias "Source"` when source notes follow a horizontal rule.
    pandoc_input_fmt = 'markdown-yaml_metadata_block'

    cmd = [
        'pandoc',
        str(input_path),
        '--from', pandoc_input_fmt,
        '--to', 'docx',
        '--output', str(output_path),
    ]
    pagebreak_filter = Path(__file__).parent / 'pagebreak.lua'
    if pagebreak_filter.exists():
        cmd += ['--lua-filter', str(pagebreak_filter)]
    if reference and reference.exists():
        cmd += ['--reference-doc', str(reference)]
    if toc:
        cmd += ['--toc', f'--toc-depth={toc_depth}']
    return cmd


def merge_markdown_files(files: Iterable[Path], dest: Path) -> None:
    with dest.open('w', encoding='utf-8') as out:
        for f in files:
            out.write(f.read_text(encoding='utf-8'))
            out.write('\n\n')
            # Removed: section breaks are now added in post-processing

def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser()
    parser.add_argument('--input', required=True, help='Input file or folder containing markdown')
    parser.add_argument('--output', default='output.docx', help='Output DOCX filename')
    parser.add_argument('--reference', default='reference.docx', help='Reference DOCX for styles')
    parser.add_argument('--toc', action='store_true', help='Include Table of Contents')
    parser.add_argument('--toc-depth', type=int, default=2, help='TOC depth')
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = _build_parser()
    args = parser.parse_args(argv)

    check_pandoc()

    src_path = Path(args.input)
    dest_path = Path(args.output)
    reference_path = Path(args.reference)

    temp_dir = None
    try:
        if src_path.is_dir():
            md_files = sorted([p for p in src_path.glob('*.md')])
            if not md_files:
                print('No markdown files found in directory')
                sys.exit(1)
            temp_dir = tempfile.TemporaryDirectory()
            temp_md = Path(temp_dir.name) / 'merged.md'
            merge_markdown_files(md_files, temp_md)
            pandoc_cmd = build_pandoc_cmd(
                temp_md,
                dest_path,
                reference_path,
                args.toc,
                args.toc_depth,
            )
        else:
            pandoc_cmd = build_pandoc_cmd(
                src_path,
                dest_path,
                reference_path,
                args.toc,
                args.toc_depth,
            )

        print('Running:', ' '.join(map(str, pandoc_cmd)))
        subprocess.run(pandoc_cmd, check=True)
        # Post-process: add section breaks for TOC/units/file boundaries
        try:
            from .postprocess_docx import insert_section_after_toc
        except ImportError:
            from postprocess_docx import insert_section_after_toc
        try:
            insert_section_after_toc(dest_path, has_toc=args.toc)
        except (OSError, RuntimeError, ValueError):
            pass
        print('Wrote', dest_path)
    finally:
        if temp_dir:
            temp_dir.cleanup()
    return 0


if __name__ == '__main__':
    sys.exit(main())
