"""
Claude edit
Simple CLI wrapper that calls `pandoc` to convert Markdown to DOCX using a `reference.docx`.
- Requires `pandoc` installed and on PATH.
- Produces a `.docx` with an autogenerated TOC when `--toc` is set.

Usage example:
python scripts/cli.py --input "chapter1.md" --output "Book.docx" --reference reference.docx --toc
"""
from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Iterable, List


WORKSPACE_ROOT = Path(__file__).resolve().parent.parent


def check_pandoc() -> None:
    if shutil.which('pandoc') is None:
        print('Error: pandoc binary not found on PATH. Install from https://pandoc.org/installing.html')
        sys.exit(2)


def get_caller_cwd() -> Path:
    raw_cwd = os.environ.get('TEXTMAKER_CALLER_CWD')
    if raw_cwd:
        return Path(raw_cwd)
    return Path.cwd()


def is_windows_fallback_cwd(path: Path) -> bool:
    windows_dir = Path(os.environ.get('WINDIR', r'C:\Windows')).resolve()
    try:
        resolved = path.resolve()
    except OSError:
        return False
    return resolved == windows_dir or resolved == windows_dir / 'System32'


def resolve_user_path(raw_path: str, *, base_dir: Path) -> Path:
    path = Path(raw_path)
    if path.is_absolute():
        return path.resolve(strict=False)
    return (base_dir / path).resolve(strict=False)


def path_suffix_parts(raw_path: str) -> tuple[str, ...]:
    parts = []
    for part in Path(raw_path).parts:
        if part in ('.', ''):
            continue
        parts.append(part.lower())
    return tuple(parts)


def match_path_suffix(candidate: Path, suffix_parts: tuple[str, ...]) -> bool:
    candidate_parts = tuple(part.lower() for part in candidate.parts)
    if len(candidate_parts) < len(suffix_parts):
        return False
    return candidate_parts[-len(suffix_parts):] == suffix_parts


def infer_base_dir(raw_path: str, matched_path: Path) -> Path | None:
    suffix_parts = path_suffix_parts(raw_path)
    if not suffix_parts:
        return matched_path.parent
    parent = matched_path
    for _ in suffix_parts:
        parent = parent.parent
    return parent


def iter_candidate_base_dirs() -> Iterable[Path]:
    roots = [WORKSPACE_ROOT.parent, WORKSPACE_ROOT]
    seen: set[str] = set()
    for root in roots:
        root_key = str(root).lower()
        if root_key in seen or not root.exists():
            continue
        seen.add(root_key)
        yield root

        try:
            children = [child for child in root.iterdir() if child.is_dir()]
        except OSError:
            continue

        for child in children:
            child_key = str(child).lower()
            if child_key not in seen:
                seen.add(child_key)
                yield child

            try:
                grandchildren = [grandchild for grandchild in child.iterdir() if grandchild.is_dir()]
            except OSError:
                continue

            for grandchild in grandchildren:
                grandchild_key = str(grandchild).lower()
                if grandchild_key in seen:
                    continue
                seen.add(grandchild_key)
                yield grandchild


def search_for_existing_path(raw_path: str) -> tuple[Path | None, Path | None]:
    relative_path = Path(raw_path)
    if not relative_path.name:
        return None, None

    matches: list[Path] = []
    for base_dir in iter_candidate_base_dirs():
        candidate = base_dir / relative_path
        if candidate.exists():
            matches.append(candidate)
    if len(matches) == 1:
        match = matches[0].resolve(strict=False)
        return match, infer_base_dir(raw_path, match)
    return None, None


def resolve_existing_path(raw_path: str, *, base_dir: Path) -> tuple[Path, Path | None]:
    path = Path(raw_path)
    if path.is_absolute():
        normalized = path.resolve(strict=False)
        return normalized, normalized.parent

    direct = base_dir / path
    if direct.exists():
        normalized = direct.resolve(strict=False)
        return normalized, base_dir.resolve(strict=False)

    cwd_path = Path.cwd() / path
    if cwd_path.exists():
        normalized = cwd_path.resolve(strict=False)
        return normalized, Path.cwd().resolve(strict=False)

    searched, inferred_base = search_for_existing_path(raw_path)
    if searched is not None:
        return searched, inferred_base

    return direct, None


def build_pandoc_cmd(
    input_path: Path,
    output_path: Path,
    reference: Path,
    toc: bool,
    toc_depth: int,
    lua_filters: Iterable[Path] = (),
    use_pagebreak_filter: bool = True,
) -> List[str]:
    pandoc_input_fmt = 'markdown+fancy_lists'

    cmd = [
        'pandoc',
        str(input_path),
        '--from', pandoc_input_fmt,
        '--to', 'docx',
        '--output', str(output_path),
    ]
    pagebreak_filter = Path(__file__).parent / 'pagebreak.lua'
    if use_pagebreak_filter and pagebreak_filter.exists():
        cmd += ['--lua-filter', str(pagebreak_filter)]
    for lua_filter in lua_filters:
        cmd += ['--lua-filter', str(lua_filter)]
    if reference and reference.exists():
        cmd += ['--reference-doc', str(reference)]
    if toc:
        cmd += ['--toc', f'--toc-depth={toc_depth}']
    return cmd


_HTML_ONLY_LINE_RE = re.compile(r'^\s*(?:<[^>]+>\s*)+$')
_HORIZONTAL_RULE_RE = re.compile(r'^\s{0,3}(?:-{3,}|\*{3,}|_{3,})\s*$')
_BULLET_LIST_RE = re.compile(r'^\s*[-+*]\s+')
_ORDERED_LIST_RE = re.compile(r'^\s*\d+[.)]\s+')
_HEADING_RE = re.compile(r'^\s*#{1,6}\s+')


def _is_list_item(line: str) -> bool:
    return bool(_BULLET_LIST_RE.match(line) or _ORDERED_LIST_RE.match(line))


def _needs_blank_line_before_list(prev_line: str, current_line: str) -> bool:
    if not _is_list_item(current_line):
        return False
    stripped_prev = prev_line.strip()
    if not stripped_prev:
        return False
    if _is_list_item(prev_line):
        return False
    if _HEADING_RE.match(prev_line):
        return False
    if _HORIZONTAL_RULE_RE.match(prev_line):
        return False
    return True


def normalize_markdown(md_text: str, *, ignore_horizontal_rules: bool = False) -> str:
    """
    Normalize markdown for Pandoc by:
    - optionally removing standalone horizontal-rule lines
    - inserting a blank line before a list that directly follows prose
    - inserting a blank line after standalone HTML-only lines when immediately
      followed by non-blank markdown content

    Pandoc can otherwise treat the following markdown as part of the HTML block,
    e.g. '<a id="x"></a>' followed by '## Heading' on the next line.
    """
    lines = md_text.splitlines()
    out: list[str] = []
    for idx, line in enumerate(lines):
        if ignore_horizontal_rules and _HORIZONTAL_RULE_RE.match(line):
            continue

        if out and _needs_blank_line_before_list(out[-1], line):
            out.append('')

        out.append(line)
        if idx + 1 >= len(lines):
            continue
        next_line = lines[idx + 1]
        if ignore_horizontal_rules and _HORIZONTAL_RULE_RE.match(next_line):
            continue
        if not _HTML_ONLY_LINE_RE.match(line):
            continue
        if next_line.strip() == '':
            continue
        out.append('')
    return '\n'.join(out) + ('\n' if md_text.endswith('\n') else '')


def archive_previous_outputs(dest_path: Path) -> None:
    """Move any existing DOCX/PDF files in dest_path's folder that share the
    same base stem (ignoring trailing _outline or similar suffixes) into a
    sibling 'bak' folder, keeping the working folder clean.

    Pattern: files whose stem starts with the dest stem up to the date portion
    (everything up to and including the _MMDD component) are treated as prior
    outputs and archived.  The current dest_path itself is not yet written, so
    it is safe to match on existence.
    """
    folder = dest_path.parent
    bak_dir = folder.parent / 'bak'

    # Derive the date-prefix from the dest stem, e.g. "aw-int-all_0519"
    # by taking everything up to and including an _MMDD or _MMDD_ segment.
    import re as _re
    stem = dest_path.stem
    m = _re.match(r'^(.+_\d{4})', stem)
    date_prefix = m.group(1) if m else stem

    targets = [
        p for p in folder.iterdir()
        if p.suffix.lower() in ('.docx', '.pdf')
        and p.stem.startswith(date_prefix)
        and p != dest_path
    ]
    if not targets:
        return

    bak_dir.mkdir(parents=True, exist_ok=True)
    for p in targets:
        dest = bak_dir / p.name
        # Avoid silently overwriting an identically named bak file
        if dest.exists():
            dest = bak_dir / (p.stem + '_prev' + p.suffix)
        shutil.move(str(p), str(dest))
        print(f'Archived {p.name} → bak/')


def merge_markdown_files(
    files: Iterable[Path],
    dest: Path,
    *,
    ignore_horizontal_rules: bool = False,
) -> None:
    with dest.open('w', encoding='utf-8') as out:
        for f in files:
            source = f.read_text(encoding='utf-8')
            out.write(
                normalize_markdown(
                    source,
                    ignore_horizontal_rules=ignore_horizontal_rules,
                )
            )
            out.write('\n\n')
            # Removed: section breaks are now added in post-processing

def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser()
    parser.add_argument('--input', required=True, help='Input file or folder containing markdown')
    parser.add_argument('--output', default='output.docx', help='Output DOCX filename')
    parser.add_argument('--reference', default='reference.docx', help='Reference DOCX for styles')
    parser.add_argument('--toc', action='store_true', help='Include Table of Contents')
    parser.add_argument('--toc-depth', type=int, default=2, help='TOC depth')
    parser.add_argument(
        '--ignore-horizontal-rules',
        action='store_true',
        help='Drop standalone markdown horizontal-rule lines such as --- before conversion.',
    )
    parser.add_argument(
        '--apply-semantic-labels',
        action='store_true',
        help=(
            'Apply semantic Div label rendering during postprocessing '
            '(emoji, character styles, unit title tables). Off by default.'
        ),
    )
    parser.add_argument(
        '--no-semantic-formatting',
        action='store_true',
        help='Deprecated. Semantic formatting is off by default; use --apply-semantic-labels to enable it.',
    )
    parser.add_argument(
        '--tag-style',
        choices=['filled', 'outline'],
        default='filled',
        help='Which tag icon variant to insert before Div label text (default: filled).',
    )
    parser.add_argument(
        '--building-block-template',
        help='Word template containing Quick Parts to insert during postprocessing.',
    )
    parser.add_argument(
        '--lua-filter',
        action='append',
        default=[],
        help='Additional Pandoc Lua filter path. Can be supplied multiple times.',
    )
    parser.add_argument(
        '--h1-sections',
        action='store_true',
        default=False,
        help='Insert nextPage section breaks before H1 headings (opt-in). Omit when the reference DOCX already sets pageBreakBefore on Heading 1.',
    )
    parser.add_argument(
        '--no-pagebreak-filter',
        action='store_true',
        help='Do not apply textmaker built-in pagebreak.lua during Pandoc conversion.',
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = _build_parser()
    args = parser.parse_args(argv)

    check_pandoc()

    caller_cwd = get_caller_cwd()
    preferred_base = caller_cwd
    if is_windows_fallback_cwd(preferred_base):
        preferred_base = WORKSPACE_ROOT

    src_path, src_base = resolve_existing_path(args.input, base_dir=preferred_base)
    reference_path, reference_base = resolve_existing_path(args.reference, base_dir=preferred_base)
    lua_filter_paths = [
        resolve_existing_path(raw_filter, base_dir=preferred_base)[0]
        for raw_filter in args.lua_filter
    ]

    output_base = preferred_base
    if src_base and reference_base and src_base == reference_base:
        output_base = src_base
    elif src_base:
        output_base = src_base
    elif reference_base:
        output_base = reference_base
    dest_path = resolve_user_path(args.output, base_dir=output_base)

    temp_dir = None
    try:
        if src_path.is_dir():
            md_files = sorted([p for p in src_path.glob('*.md')])
            if not md_files:
                print('No markdown files found in directory')
                sys.exit(1)
            temp_dir = tempfile.TemporaryDirectory()
            temp_md = Path(temp_dir.name) / 'merged.md'
            merge_markdown_files(
                md_files,
                temp_md,
                ignore_horizontal_rules=args.ignore_horizontal_rules,
            )
            pandoc_cmd = build_pandoc_cmd(
                temp_md,
                dest_path,
                reference_path,
                args.toc,
                args.toc_depth,
                lua_filter_paths,
                not args.no_pagebreak_filter,
            )
        else:
            temp_dir = tempfile.TemporaryDirectory()
            temp_md = Path(temp_dir.name) / src_path.name
            source = src_path.read_text(encoding='utf-8')
            temp_md.write_text(
                normalize_markdown(
                    source,
                    ignore_horizontal_rules=args.ignore_horizontal_rules,
                ),
                encoding='utf-8',
            )
            pandoc_cmd = build_pandoc_cmd(
                temp_md,
                dest_path,
                reference_path,
                args.toc,
                args.toc_depth,
                lua_filter_paths,
                not args.no_pagebreak_filter,
            )

        print('Running:', ' '.join(map(str, pandoc_cmd)))
        dest_path.parent.mkdir(parents=True, exist_ok=True)
        archive_previous_outputs(dest_path)
        subprocess.run(pandoc_cmd, check=True)
        # Post-process: add section breaks for TOC/units/file boundaries
        try:
            from .postprocess_docx import insert_section_after_toc
        except ImportError:
            from postprocess_docx import insert_section_after_toc
        insert_section_after_toc(
            dest_path,
            has_toc=args.toc,
            insert_h1_sections=args.h1_sections,
            reference_doc_path=reference_path,
            apply_semantic_labels=args.apply_semantic_labels,
            building_block_template=args.building_block_template,
            tag_style=args.tag_style,
        )
        print('Wrote', dest_path)
    finally:
        if temp_dir:
            temp_dir.cleanup()
    return 0


if __name__ == '__main__':
    sys.exit(main())
