"""
Claude edit
Simple CLI wrapper that calls `pandoc` to convert Markdown to DOCX using a `reference.docx`.
- Requires `pandoc` installed and on PATH.
- Produces a `.docx` with an autogenerated TOC when `--toc` is set.

Usage example:
python scripts/cli.py --input "chapter1.md" --output "Book.docx" --reference reference.docx --toc
"""
import argparse
import shutil
import subprocess
import sys
from pathlib import Path


def check_pandoc():
    if shutil.which('pandoc') is None:
        print('Error: pandoc binary not found on PATH. Install from https://pandoc.org/installing.html')
        sys.exit(2)


def build_pandoc_cmd(input_path: Path, output_path: Path, reference: Path, toc: bool, toc_depth: int):
    cmd = [
        'pandoc',
        str(input_path),
        # Enable page breaks via the pagebreaks extension
        '--from', 'markdown+pagebreaks',
        '--to', 'docx',
        '--output', str(output_path),
    ]
    if reference and reference.exists():
        cmd += ['--reference-doc', str(reference)]
    if toc:
        cmd += ['--toc', f'--toc-depth={toc_depth}']
    return cmd


def merge_markdown_files(files, dest: Path):
    with dest.open('w', encoding='utf-8') as out:
        for idx, f in enumerate(files):
            out.write(f.read_text(encoding='utf-8'))
            out.write('\n\n')
            # Removed: section breaks are now added in post-processing

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--input', required=True, help='Input file or folder containing markdown')
    parser.add_argument('--output', default='output.docx', help='Output DOCX filename')
    parser.add_argument('--reference', default='reference.docx', help='Reference DOCX for styles')
    parser.add_argument('--toc', action='store_true', help='Include Table of Contents')
    parser.add_argument('--toc-depth', type=int, default=2, help='TOC depth')
    args = parser.parse_args()

    check_pandoc()

    input_path = Path(args.input)
    output_path = Path(args.output)
    reference = Path(args.reference)

    if input_path.is_dir():
        md_files = sorted([p for p in input_path.glob('*.md')])
        if not md_files:
            print('No markdown files found in directory')
            sys.exit(1)
        temp = Path('.autotext_temp.md')
        merge_markdown_files(md_files, temp)
        cmd = build_pandoc_cmd(temp, output_path, reference, args.toc, args.toc_depth)
    else:
        cmd = build_pandoc_cmd(input_path, output_path, reference, args.toc, args.toc_depth)

    print('Running:', ' '.join(map(str, cmd)))
    subprocess.run(cmd, check=True)
    # Post-process: add section breaks for TOC/units/file boundaries
    try:
        from scripts.postprocess_docx import insert_section_after_toc
        insert_section_after_toc(output_path, has_toc=args.toc)
    except Exception:
        pass
    print('Wrote', output_path)
